/********************************** (C) COPYRIGHT *******************************
 * File Name          : led_pwm.h
 * Description        : LED brightness control on PA4 via software PWM
 *                       (TMR1 interrupt). CH592F port of
 *                       ../../ch32l103/User/led_pwm.[ch] (there PB8/TIM4_CH3
 *                       hardware PWM; PA4 on CH592F has no PWM4-11 hardware
 *                       channel routed to it, so brightness is generated by
 *                       toggling the pin from a periodic timer interrupt).
 *******************************************************************************/
#ifndef APP_LED_PWM_H_
#define APP_LED_PWM_H_

#include "CH59x_common.h"

/* Initializes PA4 as a GPIO output and starts the TMR1-driven software PWM
 * with 0% duty (LED off). */
void LED_PWM_Init(void);

/* Sets LED brightness, 0 (off) .. 255 (full brightness). */
void LED_PWM_SetBrightness(uint8_t brightness);

/* Returns the last brightness value set via LED_PWM_SetBrightness(). */
uint8_t LED_PWM_GetBrightness(void);

#endif /* APP_LED_PWM_H_ */
